src/main/java/com/umc/TheGoods/apiPayload/exception/handler/TempHandler.java
src/main/java/com/umc/TheGoods/domain/common/BaseDateTimeEntity.java
src/main/java/com/umc/TheGoods/domain/item/Item.java

error handler 예시 추가 및 도메인(item, BaseDateTimeEntity) 수정
- error handler 예시 TempHandler 추가
- item domain 세부사항 수정, stock, price nullable = true로 수정
- BaseDateTimeEntity에 어노테이션 추
추가로 refactoring 이 필요할 시 말씀주세요

🔨[refactor] error handler 예시 추가 및 도메인 수정

---

src/main/java/com/umc/TheGoods/domain/enums/OrderStatus.java
src/main/java/com/umc/TheGoods/domain/item/Item.java
src/main/java/com/umc/TheGoods/domain/order/Cart.java

장바구니, 상품 엔티티 및 OrderStatus 변경
- Cart, Item entity가 변경되어 ddl-auto:create로 실행 한 번 필요합니다.
- OrderStatus에 enum 값이 변경되었습니다.
-

[refactor/38] Cart, Item 엔티티 및 OrderStatus 변경

---

.ebextensions_dev/00-makeFiles.config
.ebextensions_dev/01-set-timezone.config
.github/workflows/dev_deploy.yml
.platform/nginx.conf
.platform/nginx/conf.d/client_max_body_size.conf
Procfile
build.gradle
src/main/java/com/umc/TheGoods/web/controller/RootController.java
src/main/resources/application.yml

CI/CD 파이프라인 구축
- CI/CD를 위한 디렉토리 및 파일이 추가되었습니다.
- health check를 위한 API가 추가되었습니다.

[Ci/46] CI/CD 파이프라인 구축 테스트

---

.platform/nginx/conf.d/client_max_body_size.conf

:construction_worker: CI/CD: client_max_body_size.conf 수정

---

src/main/resources/application.yml

:construction_worker: CI/CD: application.yml 수정

---

.ebextensions_dev/00-makeFiles.config

:construction_worker: CI/CD: KST timezone 설정

---

.github/workflows/dev_deploy.yml

:construction_worker: CI/CD: deploy.yml 수정

---

.github/workflows/dev_deploy.yml

:construction_worker: CI/CD: github secrets 적용

---

.ebextensions_dev/00-makeFiles.config
src/main/resources/application.yml

application.yml db 설정 정보 수정
- local, dev으로 application.yml 파일 분리
- ci/cd java 실행 스크립트 수정

:construction_worker: CI/CD: application.yml db 설정 정보 수정

---

.github/workflows/dev_deploy.yml
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

:construction_worker: CI/CD: application.yml 파일 분리

---

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java
src/main/java/com/umc/TheGoods/converter/item/ItemViewConverter.java
src/main/java/com/umc/TheGoods/domain/item/Item.java
src/main/java/com/umc/TheGoods/domain/mapping/ViewSearch/ItemView.java
src/main/java/com/umc/TheGoods/repository/item/ItemImgRepository.java
src/main/java/com/umc/TheGoods/repository/item/ItemOptionRepository.java
src/main/java/com/umc/TheGoods/repository/item/ItemTagRepository.java
src/main/java/com/umc/TheGoods/repository/item/ItemViewRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
src/main/java/com/umc/TheGoods/web/dto/item/ItemRequestDTO.java
src/main/java/com/umc/TheGoods/web/dto/item/ItemResponseDTO.java

상품의 상세 정보를 수정 및 상세내용 조회 API 입니다.
- 상품 수정 api 추가
- 상품 상세정보 조회 api 추

[feature] 상품 정보 수정 API & 상품 상세 정보 조회 API 구현

---

src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

로컬에서 aws ec2로 서버 이동으로 인해 redirect url 수정, 환경변수 설정
- userController 수정
- application.yml 파일 수정

:recycles: Refactor: 소셜 로그인 redirect 주소 수정, 환경변수 수정(#68)

---

src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

비밀번호 변경 api 에서 사용되는 email 인증 예외처리 추가
- 이메일 인증 환경변수 수정
- 이메일 인증 예외처리

:recycles: Refactor: 비밀번호 변경 api 수정(#70)

---

.github/workflows/dev_deploy.yml

:recycles: Refactor: 비밀번호 변경 api 관련 환경변수 수정(#70)

---

src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java
src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java

인증번호가 response에 담겨 있어서 없애야함
- 인증 요청시 response에 성공만 담김

:recycles: Refactor: 인증번호 관련 api response 수정(#74)

---

.github/workflows/dev_deploy.yml
build.gradle
src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
src/main/java/com/umc/TheGoods/aws/s3/AmazonS3Manager.java
src/main/java/com/umc/TheGoods/config/AmazonConfig.java
src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java
src/main/java/com/umc/TheGoods/domain/images/ProfileImg.java
src/main/java/com/umc/TheGoods/domain/images/Uuid.java
src/main/java/com/umc/TheGoods/domain/member/Member.java
src/main/java/com/umc/TheGoods/repository/UuidRepository.java
src/main/java/com/umc/TheGoods/repository/member/ProfileImgRepository.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/MemberController.java
src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java
src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

프로필 조회, 수정할 수 있는 api
- Entity 수정
- S3 관련 설정 파일, 환경변수 추가

:sparkles: Feat: 프로필 조회, 수정 api 구현(#48)

---

src/main/java/com/umc/TheGoods/web/controller/MemberController.java

소셜 로그인 api Http 메소드 수정
-소셜 로그인 api Http 메소드 수정

:recycle: Refactor: 소셜 로그인 api Http 메소드 수정(#82)

---

src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/MemberController.java

소셜 로그인 api Redirect Uri 수정
- 소셜 로그인 api Redirect Uri 수정

:recycle: Refactor: 소셜 로그인 api Redirect Uri 수정(#82)

---

src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/MemberController.java

소셜 로그인 api Redirect Uri 수정
- 카카오, 네이버 소셜 로그인 api Redirect Uri 수정

:recycle: Refactor: 소셜 로그인 api Redirect Uri 수정(#87)

---

src/main/resources/application-dev.yml

application-dev.yml의 ddl-auto:create를 update로 변경

:recycle: Refactor: application-dev.yml 수정

---

.github/workflows/dev_deploy.yml
build.gradle
src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/MemberController.java
src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

비밀번호 찾기 api response jwt 추가, 소셜 로그인 api 환경변수 설정
- 소셜 로그인 관련 환경변수 설정
- 비밀번호 찾기 결과에 jwt 토큰 발급

:recycle: Refactor: 비밀번호 찾기 api response jwt 추가, 소셜 로그인 api 환경변수 설정(#93)

---

.github/workflows/dev_deploy.yml

소셜로그인 관련 보안을 위해 환경변수를 설정했는데 접근이 안되어서 환경변수 관련 변수 수정

:recycle: Refactor: 소셜 로그인 api 환경변수 설정 부분 수정(#93)

---

src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java

tag 검색시 tag search 저장 오류 수정
- 변경사항 1 
- 변경사항 2 
- 변경사항 3

:bug: Bugfix: 태그 검색 오류 수정

---

src/main/java/com/umc/TheGoods/repository/member/CategoryRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/validation/validator/ItemExistValidator.java

상품 검색 및 조회 validator 수정
- 상품 검색 validator 수정
- 상품 조회 validator 수정

🔨[refactor] 상품 검색 및 조회 validator 수정

---

src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java

주문 내역 조회 API의 OptionString이 출력되지 않는 오류 수정
- 변경사항 1 
- 변경사항 2 
- 변경사항 3

:bug: BugFix: 주문 내역 조회 API 오류 수정

---

src/main/java/com/umc/TheGoods/TheGoodsApplication.java

:bug: BugFix: CI/CD 오류 수정

---

.github/workflows/dev_deploy.yml
src/main/java/com/umc/TheGoods/TheGoodsApplication.java
src/main/java/com/umc/TheGoods/web/controller/PaymentController.java
src/main/resources/application-dev.yml

포트원 환경변수 설정 및 ci/cd 에러 해결
- dev_deploy.yml
- application-dev.yml
- github secrets

[ci/cd] 포트원 환경변수 설정 및 ci/cd 에러 해결

---

src/main/java/com/umc/TheGoods/web/controller/PaymentController.java

♻️ Refactor: PaymentController 주석 수정

---

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

신상품/인기상품/마감임박상품 조회 API 구현
- item 관련 repository, service, controller, ErrorStatus가 추가되었습니다.

:sparkles: Feat: 신상품/인기상품/마감임박상품 조회 API 구현

---

src/main/java/com/umc/TheGoods/repository/item/ItemViewRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

방금 전 본 상품과 유사한 상품 추천 기능 API 구
- 방금 전 본 상품과 유사한 상품 추천 기능 추가
- category 이름으로 상품 검색 코드 수정

✨  [feature] 방금 전 본 상품과 유사한 상품 추천 기능 구현

---

src/main/java/com/umc/TheGoods/config/IamportConfig.java
src/main/java/com/umc/TheGoods/web/controller/PaymentController.java

결제 승인 API 수정
- API 엔드포인트
- swagger 명세

♻️ Refactor: 결제 승인 API 엔드포인트 및 swagger 명세 수정

---

src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java
src/main/java/com/umc/TheGoods/domain/item/Item.java
src/main/java/com/umc/TheGoods/repository/item/ItemTagRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemCommandServiceImpl.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java
src/main/java/com/umc/TheGoods/web/dto/item/ConsultResultDTO.java

태그가 많이 등록된 상품 조회 API 구현
- 태그가 많이 등록된 상품 조회 API 추가
- Swagger에 api 명세
- api uri 수정

🚀 [feature] 태그가 많이 등록된 상품 조회 API 구현

---

src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
src/main/java/com/umc/TheGoods/web/dto/cart/CartResponseDTO.java

:recycle: Refactor: 장바구니 조회 API 응답 DTO 수정

---

src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

배송예정일 순으로 상품 추천 기능 API 구현
- 배송예정일 순으로 상품 추천 기능 API 추가 
- Swagger api 명세

🚀 [feature] 라스트 찬스, 배송예정일 순으로 상품 추천 기능 API 구현

---

src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

가장 많이 판매된 상품 조회 API 구현
- 가장 많이 판매된 상품 조회 API 구현

:sparkles: Feat: 가장 많이 판매된 상품 조회 API 구현

---

src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

꾸준히 사랑받는 상품 추천 API 구현
- 꾸준히 사랑받는 상품 추천 API 구현

[feature/133] 꾸준히 사랑받는 상품 추천 API 구현

---

src/main/java/com/umc/TheGoods/config/WebConfig.java
src/main/java/com/umc/TheGoods/config/springSecurity/SpringSecurityConfig.java
src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java
src/main/java/com/umc/TheGoods/repository/member/MemberRepository.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/MemberController.java
src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java

cors 설정과 사장님 -> 손님, 손님 -> 사장님 역활 전환 api 구현
- Webconfig
- SpringSecurityConfig
- Member 관련 파일들

:sparkles: Feat: 역할 전환 api 구현, cors 설정

---

src/main/java/com/umc/TheGoods/config/WebConfig.java
src/main/java/com/umc/TheGoods/web/controller/MemberController.java

이메일 찾기 api 수정
- WebConfig
- MemberController

:Recycle: Refactor: 이메일 찾기 api 수정

---

src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

오늘의 상품 추천 API 구현
- 오늘의 상품 추천 API 구현

[feature/137] 오늘의 상품 추천 API 구현

---

src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java
src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

관련 상품 조회 API 구현
- 관련 상품 조회 API 구현

[feature/143] 관련 상품 조회 API 구현

---

src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

관련 상품 조회 API 페이징 오류 수정
- 관련 상품 조회 API 페이징 오류 수정

:bug: BugFix: 관련 상품 조회 API 페이징 오류 수정

---

src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java
src/main/java/com/umc/TheGoods/service/CartService/CartQueryService.java
src/main/java/com/umc/TheGoods/service/CartService/CartQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/CartController.java
src/main/java/com/umc/TheGoods/web/dto/cart/CartResponseDTO.java

장바구니 옵션, 상품 재고 조회 API 구현
- 장바구니 옵션, 상품 재고 조회 API 구현

:sparkles: Feat: 장바구니 옵션, 상품 재고 조회 API 구현

---

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java
src/main/java/com/umc/TheGoods/domain/member/Member.java
src/main/java/com/umc/TheGoods/domain/mypage/Account.java
src/main/java/com/umc/TheGoods/domain/mypage/Address.java
src/main/java/com/umc/TheGoods/repository/member/AccountRepository.java
src/main/java/com/umc/TheGoods/repository/member/AddressRepository.java
src/main/java/com/umc/TheGoods/repository/member/MemberRepository.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java
src/main/java/com/umc/TheGoods/web/controller/MemberController.java
src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java
src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java

회원 정보 조회 response값 추가, 회원 정보 수정 api 구현
- Member 관련된 파일들

:recycle: Refactor: 회원 정보 조회, 수정 api 기능 수정

---

src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java

주문 등록 시 주문 상태 결제 완료로 변경
- 변경사항 1 
- 변경사항 2 
- 변경사항 3

:recycle: Refactor: 주문 등록 시 주문 상태 결제 완료로 변경

---

src/main/java/com/umc/TheGoods/config/springSecurity/SpringSecurityConfig.java

springSeuciryt config 파일 수정
- ignoring 부분에 로그인 안해도 사용할 수 있어야 하는 api 추가

:bug: fix: Spring Security Config 내용 수정

---

.github/workflows/dev_deploy.yml

배포서버 환경 이전을 위한 dev_deploy.yml 파일 수정
- dev_deploy.yml 파일의 application_name, environment_name 수정

:construction_worker: CI/CD: dev_deploy.yml 수정

---

src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java

회원가입 validation 수정
- MemberRequestDTO에 joinDTO 수정

:recycle: Refactor: 회원가입 validation 수정

---

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java
src/main/java/com/umc/TheGoods/domain/member/Member.java
src/main/java/com/umc/TheGoods/repository/member/MemberRepository.java
src/main/java/com/umc/TheGoods/repository/member/WithdrawReasonRepository.java
src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java

회원 탈퇴 soft delete로 실행
- 회원 탈퇴시 item도 inactive로 변경
- 회원 탈퇴후 재가입 가능하도록 구현

♻️ refactor: 회원 탈퇴 api 수정

---

src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java

쿠키 유효 path 설정
- 쿠키 path 변경
accesstoken을 갱신할때마다 쿠키도 함께 갱신해줘서 보안을 높이는 방법을 사용했는데 쿠키 허용 path를 모든 범위로 해서 보안상 문제가 될 수 있는지

:recycle: Refactor: Cookie 설정 변경

---

src/main/java/com/umc/TheGoods/config/springSecurity/SpringSecurityConfig.java
src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java

상품 조회 API 수정
- 상품 상세 조회 API 엔드포인트 변경
(변경 전)
/api/seller/item/{itemId}
(변경 후)
/api/item/{itemId}
- 사용하지 않는 API 제거
- 꾸준히 사랑받는 제품 추천  (/item/steady)
- 태그가 많이 달려있는 상품 추천 (/count/tags/item)
- 배송기간이 빠른 상품 추천 (/delivery-date/item)

:recycle: Refactor: 상품 조회 API 수정

---

src/main/java/com/umc/TheGoods/config/springSecurity/SpringSecurityConfig.java

상품 상세 조회 API 호출 시 security 권한 오류 발생하는 문제 해결
- spring security config 수정

:bug: bug: SpringSecurityConfig 수정
