THEGOODs-repo/server

src/main/java/com/umc/TheGoods/apiPayload/ApiResponse.java, src/main/java/com/umc/TheGoods/apiPayload/code/BaseCode.java, src/main/java/com/umc/TheGoods/apiPayload/code/BaseErrorCode.java, src/main/java/com/umc/TheGoods/apiPayload/code/ErrorReasonDTO.java, src/main/java/com/umc/TheGoods/apiPayload/code/ReasonDTO.java, src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/apiPayload/code/status/SuccessStatus.java, src/main/java/com/umc/TheGoods/apiPayload/exception/ExceptionAdvice.java, src/main/java/com/umc/TheGoods/apiPayload/exception/GeneralException.java
api 응답 통일, 에러 처리 구현
- apiPayload 코드 추가
- error handler 및 error 형태 추가
추후 진행하면서 각자 도메인에서 발생할 error에 대해 명세하면서 구현 진행하시면 될 것 같습니다. 
혹여 진행하면서 api 응답이나 에러에 관련하여 문제가 발생하면 말씀주시면 됩니다.
=> 🚀 [feature] api 응답 통일, 에러 처리 구현

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java, src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java, src/main/java/com/umc/TheGoods/domain/enums/MemberRole.java, src/main/java/com/umc/TheGoods/domain/item/Item.java, src/main/java/com/umc/TheGoods/domain/item/Review.java, src/main/java/com/umc/TheGoods/domain/order/OrderCancel.java, src/main/java/com/umc/TheGoods/domain/order/OrderDetail.java, src/main/java/com/umc/TheGoods/domain/order/OrderItem.java, src/main/java/com/umc/TheGoods/domain/order/Orders.java, src/main/java/com/umc/TheGoods/repository/order/OrderItemRepository.java, src/main/java/com/umc/TheGoods/service/CategoryService/CategoryQueryServiceImpl.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java, src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandServiceImpl.java, src/main/java/com/umc/TheGoods/validation/validator/OrderAvailableValidator.java, src/main/java/com/umc/TheGoods/web/controller/OrderController.java, src/main/java/com/umc/TheGoods/web/controller/TestController.java, src/main/java/com/umc/TheGoods/web/dto/item/ItemRequestDTO.java, src/main/java/com/umc/TheGoods/web/dto/order/OrderRequestDTO.java
주문 내역 조회 페이지에서 관리되는 주문 내역의 단위가 "주문한 상품 옵션" 단위에서 "주문한 상품" 단위로 변경됨에 따라 주문 도메인 및 주문 등록 API를 수정했습니다. 비회원 주문을 등록하는 기능이 추가되었습니다.
- Entity 설정 변경으로 인해 ddl-auto:create로 실행 한 번 필요합니다.
- OrderItem entity가 추가됨에 따라 다른 주문 관련 entity도 변경되었습니다. 
- 주문 관련 converter, repository, service, converter, validator가 변경되었습니다.
- db에 회원, 상품, 상품 옵션 관련 dummy data를 추가해주는 테스트용 api가 추가되었습니다.
작업 편의를 위해서 테스트용 데이터 세팅 api를 만들었습니다..
ddl-auto:create를 하면 기존에 테스트하던 데이터들이 모두 사라지는데, 이 때 회원, 상품, 상품 옵션 관련 dummy data를 추가해주는 api를 사용해 테스트 데이터를 세팅할 수 있습니다.
GET /api/setTestData를 실행하면 3개의 회원 계정이 생성 되고, 상품 데이터 3개와 상품 옵션 데이터 5개가 생성됩니다.
Swagger에 해당 api 명세를 참고해주시고 이해가 안되신다면 따로 질문 부탁드려요..!
=> [refactor/28] 상품 주문 API 수정

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java, src/main/java/com/umc/TheGoods/domain/order/OrderItem.java, src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandService.java, src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandServiceImpl.java, src/main/java/com/umc/TheGoods/service/OrderService/OrderQueryServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/OrderController.java, src/main/java/com/umc/TheGoods/web/dto/order/OrderRequestDTO.java, src/main/java/com/umc/TheGoods/web/dto/order/OrderResponseDTO.java
주문 구매 확정 API 구현
- 주문 관련 DTO, converter, repository, service, converter, validator, ErrorStatus가 추가되었습니다. 
커밋 히스토리에 보시면 주문 배송지 정보 수정, 환불 계좌 정보 수정 API 구현 내역이 같이 들어가 있는데 제가 로컬 브랜치랑 내용 동기화시키는 과정에서 생긴 커밋들입니다.. 이 pr에서는 해당 API 코드들은 모두 삭제하고 merge 요청 드립니다..! 정보 수정 api는 다른 브랜치에서 pr 따로 드릴게요
=> [feature/40] 주문 구매 확정 API 구현

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java, src/main/java/com/umc/TheGoods/domain/order/Cart.java, src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java, src/main/java/com/umc/TheGoods/service/CartService/CartCommandService.java, src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java, src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java, src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java, src/main/java/com/umc/TheGoods/validation/annotation/ExistItem.java, src/main/java/com/umc/TheGoods/validation/annotation/ExistItemOption.java, src/main/java/com/umc/TheGoods/validation/validator/ItemExistValidator.java, src/main/java/com/umc/TheGoods/validation/validator/ItemOptionExistValidator.java, src/main/java/com/umc/TheGoods/validation/validator/OrderAvailableValidator.java, src/main/java/com/umc/TheGoods/web/controller/CartController.java, src/main/java/com/umc/TheGoods/web/dto/cart/CartRequestDTO.java
장바구니 등록 API 구현
- cart 관련 DTO, converter, repository, service, converter, validator, ErrorStatus가 추가되었습니다.
현재 장바구니 추가 메소드에는 cart 테이블에 해당 상품/옵션에 대한 장바구니 내역 이미 존재하면, 해당 내역의 담은 수량만 업데이트하는 부분 추가 구현이 필요합니다. 장바구니 옵션 수정 api 개발 후 해당 부분도 추가해서 pr 드리겠습니다!
=> [feature/42] 장바구니 등록 API 구현

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/domain/order/Cart.java, src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java, src/main/java/com/umc/TheGoods/service/CartService/CartCommandService.java, src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java, src/main/java/com/umc/TheGoods/service/CartService/CartQueryService.java, src/main/java/com/umc/TheGoods/service/CartService/CartQueryServiceImpl.java, src/main/java/com/umc/TheGoods/validation/annotation/ExistCart.java, src/main/java/com/umc/TheGoods/validation/validator/CartExistValidator.java, src/main/java/com/umc/TheGoods/web/controller/CartController.java, src/main/java/com/umc/TheGoods/web/dto/cart/CartRequestDTO.java
장바구니 옵션 수정 API 구현 및 기존 장바구니 담기 API 로직 수정
- 장바구니 관련 DTO, converter, repository, service, converter, validator, ErrorStatus가 추가되었습니다.
- 기존 장바구니 담기 API 서비스 로직이 변경되었습니다.
장바구니 담기, 옵션 수정 서비스 로직이 검증 코드가 많아서 가독성이 조금 떨어질 수 있을 것 같은데,, 이 부분은 추후에 리팩토링 해보도록 하겠습니다..ㅠㅠ
=> [feature/44] 장바구니 옵션 수정 API 구현

src/main/java/com/umc/TheGoods/config/MailConfig.java, src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java, src/main/java/com/umc/TheGoods/repository/member/MemberRepository.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/MemberController.java, src/main/java/com/umc/TheGoods/web/dto/member/KakaoProfile.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java, src/main/java/com/umc/TheGoods/web/dto/member/NaverProfile.java, src/main/java/com/umc/TheGoods/web/dto/member/OAuthToken.java
소셜 로그인 구현
- MemberController, MemberService,DTO추가
- EmailConfig 수정
=> :sparkles: Feat: 소셜 로그인 구현(카카오, 네이버)(#36)

src/main/java/com/umc/TheGoods/domain/community/Comment.java, src/main/java/com/umc/TheGoods/domain/community/Inquiry.java, src/main/java/com/umc/TheGoods/domain/member/Member.java, src/main/java/com/umc/TheGoods/repository/PostRepository.java, src/main/java/com/umc/TheGoods/service/PostService/PostCommandService.java, src/main/java/com/umc/TheGoods/service/PostService/PostCommandServiceImpl.java, src/main/java/com/umc/TheGoods/service/PostService/PostQueryService.java, src/main/java/com/umc/TheGoods/service/PostService/PostQueryServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/PostController.java, src/main/java/com/umc/TheGoods/web/dto/post/PostRequestDto.java, src/main/java/com/umc/TheGoods/web/dto/post/PostResponseDto.java
좋아요 순으로 내림차순 정렬 후, 인기 사장님 포스트 조회 API
Notion Endpoint 및 API 명세 참고
데모데이를 위한 결제 기능 우선 개발 예정
=> [feature/10] 인기 피드 전체 조회

src/main/java/com/umc/TheGoods/converter/item/ItemConverter.java, src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java, src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryService.java, src/main/java/com/umc/TheGoods/service/ItemService/ItemQueryServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/ItemRestController.java, src/main/java/com/umc/TheGoods/web/dto/item/ItemResponseDTO.java
판매자의 판매 상품을 조회하는 API 입니다.
- 판매자 본인이 판매하고 있는 상품들을 조회하는 API 추가
=> [feature] 판매 상품 조회 API 구현

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java, src/main/java/com/umc/TheGoods/domain/item/ItemOption.java, src/main/java/com/umc/TheGoods/domain/order/Cart.java, src/main/java/com/umc/TheGoods/domain/order/CartDetail.java, src/main/java/com/umc/TheGoods/repository/cart/CartDetailRepository.java, src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java, src/main/java/com/umc/TheGoods/service/CartService/CartCommandService.java, src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java, src/main/java/com/umc/TheGoods/service/CartService/CartQueryService.java, src/main/java/com/umc/TheGoods/service/CartService/CartQueryServiceImpl.java, src/main/java/com/umc/TheGoods/validation/annotation/ExistCartDetail.java, src/main/java/com/umc/TheGoods/validation/validator/CartDetailExistValidator.java, src/main/java/com/umc/TheGoods/web/controller/CartController.java, src/main/java/com/umc/TheGoods/web/dto/cart/CartRequestDTO.java, src/main/java/com/umc/TheGoods/web/dto/cart/CartResponseDTO.java, src/main/resources/application-dev.yml
장바구니 내역 조회 API 구현 및 기존 장바구니 등록 API, 장바구니 옵션 수정 API 수정
장바구니 엔티티를 장바구니 - 장바구니 상세 엔티티로 분리
- 엔티티 변경으로 인해 개발 서버의 application-dev.yml을 ddl-auto: create로 설정했습니다.
- CartDetail(장바구니 상세 내역) 엔티티가 추가되었습니다.
- Cart <-> ItemOption 엔티티 간 연관관계가 CartDetail <-> ItemOption으로 변경되었습니다.
- cart 관련 DTO, converter, repository, service, converter, validator, ErrorStatus가 추가되었습니다.
엔티티 변경으로 인해 로컬 db ddl-auto: create 한 번 필요합니다..
개발 서버는 지금 merge 되면서 재생성 시켜야해서 create로 바꿔 두었는데, 다음 pr 하실 때 다시 update로 바꿔주신 후 pr merge 해주시면 될 것 같아요!
=> [feature/67] 장바구니 조회 API 구현 & 장바구니 등록/수정 API 수정

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/aws/s3/AmazonS3Manager.java, src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java, src/main/java/com/umc/TheGoods/domain/member/Member.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/MemberController.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
비밀번호 변경 api 구현
- setter 사용해서 데이터 변경했던 로직들 변경
=> :sparkles: Feat: 새로운 비밀번호 설정 api 구현(#80)

src/main/java/com/umc/TheGoods/converter/cart/CartConverter.java, src/main/java/com/umc/TheGoods/converter/order/OrderConverter.java
장바구니 내역 조회 API의 응답에 이미지 url 포함하도록 수정
주문 내역 조회 API의 응답에 이미지 url 포함하도록 수정
- 장바구니 내역 조회 API의 응답에 이미지 url 포함하도록 수정
- 주문 내역 조회 API의 응답에 이미지 url 포함하도록 수정
=> :recycle: Refactor: 장바구니 내역 조회, 주문 내역 조회 API 수정

src/main/java/com/umc/TheGoods/domain/images/ProfileImg.java, src/main/java/com/umc/TheGoods/domain/member/Member.java, src/main/java/com/umc/TheGoods/repository/item/CategoryTagRepository.java, src/main/java/com/umc/TheGoods/test/TestController.java, src/main/java/com/umc/TheGoods/test/TestConverter.java, src/main/java/com/umc/TheGoods/test/service/TestCommandServiceImpl.java
상품 데이터 세팅 API 수정
- 크롤링된 상품 데이터들 중 옵션이 10개 이하, 상품 이미지 개수가 20개 이하인 데이터만 필터링
- 상품 등록 시, 카테고리-태그를 다대다 관계로 저장하도록 변경
- 회원-회원프로필 간의 연관관계 설정
=> :recycle: Refactor: 상품 데이터 세팅 API 수정

src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java, src/main/java/com/umc/TheGoods/domain/mypage/Account.java, src/main/java/com/umc/TheGoods/domain/mypage/Address.java, src/main/java/com/umc/TheGoods/repository/member/AccountRepository.java, src/main/java/com/umc/TheGoods/repository/member/AddressRepository.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/MemberController.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
프로필 조회 response 수정
계좌, 배송지 다중 등록 가능하게 변경
- Member 관련 파일들
=> :recycle: Refactor: 프로필 조회 response 수정, 계좌 배송지 다중 등록 가능하게 변경

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/apiPayload/code/status/SuccessStatus.java, src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java, src/main/java/com/umc/TheGoods/domain/enums/ItemStatus.java, src/main/java/com/umc/TheGoods/domain/item/Item.java, src/main/java/com/umc/TheGoods/domain/mapping/member/MemberTag.java, src/main/java/com/umc/TheGoods/domain/member/Member.java, src/main/java/com/umc/TheGoods/repository/item/CategoryTagRepository.java, src/main/java/com/umc/TheGoods/repository/item/ItemRepository.java, src/main/java/com/umc/TheGoods/repository/member/AccountRepository.java, src/main/java/com/umc/TheGoods/repository/member/CategoryRepository.java, src/main/java/com/umc/TheGoods/repository/member/ContactTimeRepository.java, src/main/java/com/umc/TheGoods/repository/member/DeclarationRepository.java, src/main/java/com/umc/TheGoods/repository/member/MemberCategoryRepository.java, src/main/java/com/umc/TheGoods/repository/member/MemberRepository.java, src/main/java/com/umc/TheGoods/repository/member/MemberTagRepository.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryService.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberQueryServiceImpl.java, src/main/java/com/umc/TheGoods/service/OrderService/OrderQueryService.java, src/main/java/com/umc/TheGoods/service/OrderService/OrderQueryServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/MemberController.java, src/main/java/com/umc/TheGoods/web/controller/MyPageController.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberRequestDTO.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
Mypage에서 사용되는 api 구현
- MyPage Controller 추가
- MemberTag 추가
=> MyPage 기능 관련 api 구현

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/apiPayload/code/status/SuccessStatus.java, src/main/java/com/umc/TheGoods/apiPayload/exception/handler/PostHandler.java, src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java, src/main/java/com/umc/TheGoods/converter/post/PostConverter.java, src/main/java/com/umc/TheGoods/domain/member/Follow.java, src/main/java/com/umc/TheGoods/domain/member/Member.java, src/main/java/com/umc/TheGoods/repository/post/FollowRepository.java, src/main/java/com/umc/TheGoods/service/PostService/PostCommandService.java, src/main/java/com/umc/TheGoods/service/PostService/PostCommandServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/MemberController.java, src/main/java/com/umc/TheGoods/web/controller/MyPageController.java, src/main/java/com/umc/TheGoods/web/controller/PostController.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
팔로우 기능 추가
- Follow Entity 수정
- 프로필 조회 기능 수정
=> ✨ feat: 팔로우 기능 api 추가(#168)

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/domain/order/Cart.java, src/main/java/com/umc/TheGoods/domain/order/CartDetail.java, src/main/java/com/umc/TheGoods/repository/cart/CartRepository.java, src/main/java/com/umc/TheGoods/service/CartService/CartCommandServiceImpl.java
jpa delete 쿼리가 실행되지 않는 문제 해결을 위해 deleteCart, deleteCartDetail 메소드의 로직을 수정했습니다.
- 기존 jpql로 delete 쿼리 강제 실행했던 코드 제거
- deleteCart 서비스 메소드 수정
(기존 로직) cartDetail delete -> cart delete 
(수정 후 로직) cart delete 메소드만 호출하고 cartDetail은 cascade로 자동 삭제되도록 변경
- deleteCartDetail 서비스 메소드 수정
(기존 로직) cartDetail delete -> 해당 cart의 모든 cartDetail이 삭제된 경우 cart entity delete
(수정 후 로직) 요청으로 보낸 cartDetail list와 기존에 담아둔 cart의 cartDetail list 비교 -> 해당 cart의 모든 cartDetail을 삭제하고자 한다면 cart delete 메소드만 호출하고 cartDetail은 cascade로 자동 삭제, 일부 cartDetail만을 삭제하고자 한다면 cartDetail 개별 delete
=> [Bug/166] 장바구니 상품 삭제 API 로직 수정

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/apiPayload/code/status/SuccessStatus.java, src/main/java/com/umc/TheGoods/converter/post/PostConverter.java, src/main/java/com/umc/TheGoods/domain/community/Comment.java, src/main/java/com/umc/TheGoods/domain/community/Post.java, src/main/java/com/umc/TheGoods/domain/images/PostImg.java, src/main/java/com/umc/TheGoods/domain/mapping/comment/CommentLike.java, src/main/java/com/umc/TheGoods/domain/mapping/post/PostLike.java, src/main/java/com/umc/TheGoods/repository/post/CommentLikeRepository.java, src/main/java/com/umc/TheGoods/repository/post/CommentRepository.java, src/main/java/com/umc/TheGoods/repository/post/PostImgRepository.java, src/main/java/com/umc/TheGoods/repository/post/PostLikeRepository.java, src/main/java/com/umc/TheGoods/repository/post/PostRepository.java, src/main/java/com/umc/TheGoods/service/PostService/PostCommandService.java, src/main/java/com/umc/TheGoods/service/PostService/PostCommandServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/PostController.java, src/main/java/com/umc/TheGoods/web/dto/post/PostRequestDto.java
피드 생성 및 업데이트, 댓글 달기 및 삭제, 피드 좋아요 및 댓글 좋아요 기능 구현
- Post 관련 Controller, Service, Repository
포스트는 soft delete 필요성이 있는지?
댓글은 대댓글도 같이 삭제 될 수 있어서 soft delete
=> ✨ 피드, 댓글, 좋아요 api 구현

src/main/java/com/umc/TheGoods/service/OrderService/OrderCommandServiceImpl.java, src/main/java/com/umc/TheGoods/web/dto/order/OrderRequestDTO.java
주문 등록 요청을 두 가지로 구분해 생각
- cartId를 포함한 요청: 장바구니 화면에서 상품을 선택해 주문 요청하는 경우로, 장바구니에서 해당 상품을 담은 내역을 삭제해야 함
- cartId를 포함하지 않은 요청: 상품 상세 화면에서 바로 주문하기를 통해 주문 요청 하는 경우로, 장바구니에 해당 상품이 담겨있더라도 담은 내역을 삭제하지 않음
주문 등록 요청에 cartId를 포함하도록 변경해, cartId가 포함된 요청은 장바구니 내역을 삭제하는 로직까지 추가했습니다.
- OrderRequestDTO 수정
- Order create 서비스 메소드에 장바구니 내역 삭제하는 로직 추가
=> :recycle: Refactor: 주문 등록 API 수정

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/apiPayload/code/status/SuccessStatus.java, src/main/java/com/umc/TheGoods/config/springSecurity/provider/TokenProvider.java, src/main/java/com/umc/TheGoods/converter/member/MemberConverter.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandService.java, src/main/java/com/umc/TheGoods/service/MemberService/MemberCommandServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/MemberController.java, src/main/java/com/umc/TheGoods/web/dto/member/MemberResponseDTO.java
jwt 유효기간 변경 및 전송 방법 변경
- Access Token 유효기간 6시간, Refresh Token 유효기간 30일로 변경
- Refresh Token 쿠키로 전송
=> :recycle: Refactor: jwt 유효기간 변경 및 Refresh Token 쿠키로 전송 기능 변경

src/main/java/com/umc/TheGoods/config/springSecurity/SpringSecurityConfig.java, src/main/java/com/umc/TheGoods/test/TestController.java, src/main/java/com/umc/TheGoods/test/TestConverter.java, src/main/java/com/umc/TheGoods/test/service/TestCommandService.java, src/main/java/com/umc/TheGoods/test/service/TestCommandServiceImpl.java
테스트 데이터 등록용 API 수정 및 SwaggerConfig 수정
- 테스트 데이터 등록용 API 추가
- SwaggerConfig에 "/api/seller/item/{itemId}",  "/api/setItemData", "/api/search/item" 경로는 로그인 없이도 접근 가능하도록 수정
=> [Feature/188] 테스트 데이터 등록용 API 수정

src/main/java/com/umc/TheGoods/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/TheGoods/apiPayload/exception/handler/ReviewHandler.java, src/main/java/com/umc/TheGoods/converter/review/ReviewConverter.java, src/main/java/com/umc/TheGoods/domain/item/Review.java, src/main/java/com/umc/TheGoods/domain/order/OrderItem.java, src/main/java/com/umc/TheGoods/repository/review/ReviewRepository.java, src/main/java/com/umc/TheGoods/service/ReviewService/ReviewCommandService.java, src/main/java/com/umc/TheGoods/service/ReviewService/ReviewCommandServiceImpl.java, src/main/java/com/umc/TheGoods/web/controller/ReviewController.java, src/main/java/com/umc/TheGoods/web/dto/review/ReviewRequestDTO.java, src/main/java/com/umc/TheGoods/web/dto/review/ReviewResponseDTO.java
리뷰 등록 API 구현
- 리뷰 등록 API 추가
- 관련 ErrorStatus 추가
=> [Feat/184] 리뷰 등록 API 구현
